# .streamlit/config.toml
# Streamlit configuration for the LLM ES Agent

[server]
# Server settings
headless = true
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200

[browser]
# Browser settings
gatherUsageStats = false
showErrorDetails = true

[theme]
# Theme configuration
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
# Client settings
caching = true
displayEnabled = true

[runner]
# Runner settings
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true
fastReruns = true
enforceSerializableSessionState = false

[logger]
# Logger settings
level = "info"
messageFormat = "%(asctime)s %(message)s"

[mapbox]
# Mapbox settings (if needed)
token = ""

[deprecation]
# Deprecation warnings
showfileUploaderEncoding = false
showImageFormat = false